import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("desktop entry composes explicit authoring surface controller timer and generation guard", async () => {
  const source = await readFile(new URL("../src/desktop_entry.ts", import.meta.url), "utf8");

  assert.match(source, /"Home"\s*\|\s*"Navigator"\s*\|\s*"Authoring"/);
  assert.match(source, /createDesktopDocumentAuthoringController/);
  assert.match(source, /createDesktopRevisionMetadataGenerator/);
  assert.match(source, /createNewDocument/);
  assert.match(source, /desktopClient\s*\.\s*createDocument/);
  assert.match(source, /제목 없는 문서/);
  assert.doesNotMatch(source, /Untitled Document/);
  assert.match(source, /operationIdSource:\s*\(\)\s*=>\s*`document-save-/);
  assert.match(source, /operationId:\s*`document-create-/);
  assert.doesNotMatch(source, /notes\/\$\{documentId\}\.md/);
  assert.doesNotMatch(source, /createDocument\(\{[\s\S]{0,300}(versionId|snapshotRef|path):/);
  assert.match(source, /createDocument\([\s\S]*?authoringController\.open\([\s\S]*?setAuthoringSnapshot\(snapshot\)/);
  assert.match(source, /setTimeout\([^,]+,\s*800\)/s);
  assert.match(source, /authoringGeneration/);
  assert.match(source, /createDesktopDocumentAuthoringWorkbenchElement/);
  assert.doesNotMatch(source, /desktopClient\s*\.\s*renameDocument/);
  assert.doesNotMatch(source, /titleFocusDocumentId|setTitleEditState/);
  assert.match(source, /restoreDocumentVersion[\s\S]*?operationId:[\s\S]*?expectedCurrentVersionId/);
  assert.doesNotMatch(source, /restoreDocumentVersion\(\{[\s\S]{0,500}(restoredVersionId|restoredSnapshotRef):/);
  assert.match(source, /restoreDocumentVersion[\s\S]*?listDocumentHistory/);
  assert.match(source, /primaryCommitted\s*=\s*true/);
  assert.match(source, /primaryCommitted[\s\S]{0,260}DOCUMENT_RESTORE_RECOVERY_REQUIRED/);
  assert.match(source, /retryRestoreRecovery/);
  assert.match(source, /requestRestoreConfirmation/);
  assert.match(source, /cancelRestoreConfirmation/);
  assert.match(source, /restore\.status\s*!==\s*"Confirming"/);
  assert.match(source, /onRequestRestoreConfirmation:/);
  assert.match(source, /onCancelRestoreConfirmation:/);
  assert.match(source, /operationId:\s*preview\.operationId/);
  assert.match(source, /LocalDesktopCommandClientError/);
  assert.match(source, /compareDocumentVersions\(\{/);
  assert.match(source, /queryName:\s*"compare-current-document-to-version"/);
  assert.match(source, /onCompareVersion:\s*compareAuthoringVersion/);
  assert.match(source, /onCloseDiff:\s*closeAuthoringDiff/);
  assert.match(source, /limit:\s*50/);
  assert.match(source, /cursor:\s*currentCursor/);
  assert.match(source, /page\.nextCursor/);
  assert.match(source, /new Map\(current\.entries\.map/);
  assert.match(source, /onLoadMoreHistory:\s*loadMoreAuthoringHistory/);
  assert.match(source, /queryName:\s*"compare-document-versions"/);
  assert.match(source, /leftVersionId:\s*left\.versionId/);
  assert.match(source, /rightVersionId:\s*right\.versionId/);
  assert.match(source, /diffGeneration/);
  assert.match(source, /onToggleHistoryCompareSelection:/);
  assert.match(source, /onCompareSelectedVersions:\s*compareSelectedAuthoringVersions/);
  assert.match(source, /authoringGeneration\.current\s*!==\s*requestGeneration/);
  assert.match(source, /diff:\s*\{[\s\S]{0,180}status:\s*"Loading"/);
  assert.match(source, /result\.status\s*===\s*"TooLarge"/);
  assert.match(source, /createTauriDocumentDiffOperationTransport\(bootstrapInvoke\)/);
  assert.match(source, /startDesktopDocumentDiffOperation/);
  assert.match(source, /pollDesktopDocumentDiffOperation/);
  assert.match(source, /cancelDesktopDocumentDiffOperation/);
  assert.match(source, /retryDesktopDocumentDiffOperation/);
  assert.match(source, /presentDesktopDocumentDiffOperation/);
  assert.match(source, /DOCUMENT_DIFF_OPERATION_POLL_INTERVAL_MS\s*=\s*100/);
  assert.match(source, /onCancelBackgroundDiff:\s*cancelAuthoringBackgroundDiff/);
  assert.match(source, /onRetryBackgroundDiff:\s*retryAuthoringBackgroundDiff/);
  assert.match(source, /diffGeneration\.current\s*!==\s*requestDiffGeneration/);
  assert.match(source, /attachmentDiff:\s*result\.attachmentDiff/);
  assert.doesNotMatch(
    source,
    /previewDocumentRestore\(\{[\s\S]{0,260}expectedCurrentVersionId:/,
  );
  assert.match(source, /expectedCurrentVersionId:\s*preview\.expectedCurrentVersionId/);
  assert.match(source, /onInspectorTab:[\s\S]{0,220}transitionDocumentInspector/);
  assert.match(source, /onAssetUnlinkRequest:[\s\S]{0,420}type:\s*"RequestUnlink"/);
  assert.match(source, /return createDesktopDocumentAuthoringWorkbenchElement[\s\S]*onAssetOpen:\s*\(\)\s*=>\s*\{\s*void runAssetExternalOpen\(\);\s*\}/);
  assert.match(source, /onAssetUnlinkConfirm:[\s\S]{0,900}type:\s*"ConfirmUnlink"[\s\S]{0,900}runAssetUnlink/);
  assert.match(source, /mutationState\s*===\s*"Idle"[\s\S]{0,240}loadAuthoringHistory/);
  assert.match(source, /type:\s*"UnlinkSucceeded"/);
  assert.match(source, /type:\s*"UnlinkFailed"/);
  assert.doesNotMatch(source, /summary:\s*`Restore \$\{preview\.targetVersionId\}`/);
  assert.doesNotMatch(source, /Date\.now|Math\.random|localStorage|sessionStorage|process\.env/);
});
